version: 2.1
orbs:
  git: opuscapita/git@0.0.3
jobs:
  build:
    docker:
      - image: dimtass/stm32-cde-image:0.1
    steps:
      - checkout
      - run:
          name: Build firmware
          command: ./build.sh